### ISSUE TITLE
IntraACL changes to SMW

### ISSUE THREAD

**Issue by xologrim** [mediawiki4intranet/IntraACL#27]
Which changes to SMW are actually required for IntraACL? The old HaloACL only required some for property protection. 
I'm trying to find out since I want to use current versions of SMW (1.9.2 or even upcoming 2.0) with IntraACL. Perhaps I can find out, how to patch these versions...

Thanks!

Robert

**Comment by vitalif** [comment]
Fortunately their DI/IoC wrappers were replaced by something standard in SMW 2.3 :)
So you can take a look at the newer version of Mediawiki4Intranet patched SMW: https://github.com/mediawiki4intranet/SemanticMediaWiki (mw4i-2.3.x)
It has all patches ported including IntraACL one + some other improvements.
