### ISSUE TITLE
patch apply

### ISSUE THREAD

**Issue by emwa** [mediawiki4intranet/IntraACL#30]
Hello,
at this moment I'm using mediawiki 1.23.1 I see that the nearest version of the patch is 1.23.2, is there a way to know if the patch will be compatible with the latest version 1.23.6? Or It's better to update only to 1.23.2 until appears a new patch for a newer version?

thank you for the work in this project
emwa

**Comment by fedeicodip** [comment]
Hi, I upgraded to mediawiki 1.24.1. After that, when applying last patch (1.23.2) it skips some files and breaks transclusion for all pages (protectend or not). So I'm waiting for new patch...

Thank you for maintaning this extension updated
Federico

**Comment by vitalif** [comment]
see the last version, there is now a patch for 1.24
