### ISSUE TITLE
IntraACL Installation on MW v1.25.1

### ISSUE THREAD

**Issue by robert-rhys** [mediawiki4intranet/IntraACL#39]
I've been trying to install IntraACL on MediaWiki v1.25.1, but so far I have had no luck.

------------------

Here are the initial steps that I took:

1 - uploaded and then extracted the 'IntraACL-master.zip' onto my web server in the 'extensions' directory
2 - added the following 2 lines to the end of my 'LocalSettings.php' file:

   require_once('extensions/IntraACL/includes/HACL_Initialize.php');
   enableIntraACL();

3 - applied the patch though PuTTY by entering the following line from the wiki root directory:

   patch -p1 < extensions/IntraACL/patches/IntraACL-MediaWiki-1.24.1.diff

>>> since there is currently no 1.25.1 patch, I applied the 1.24.1 version, which is successful for all but a couple of items on the script

4 - ran the update tool through my web browser by using 'mw-config'

------------------

When I tried to access my wiki, I received this message:

   "A database query error has occurred. This may indicate a bug in the software."

Then I looked through the issues here on GitHub and I saw AlterDepp's issue #32, so I added another line to my 'LocalSettings.php' file, so that it looked like this:

   require_once('extensions/IntraACL/includes/HACL_Initialize.php');
   $iaclUseStoredProcedure = false;
   enableIntraACL();

I tried to access my wiki again and I received the same message as before:

   "A database query error has occurred. This may indicate a bug in the software."

I proceeded to go back to my 'LocalSettings.php' file and I commented out the 3 lines that I had added for the IntraACL installation so that it now looked like this:

   #require_once('extensions/IntraACL/includes/HACL_Initialize.php');
   #$iaclUseStoredProcedure = false;
   #enableIntraACL();

I tried to access my wiki again and now everything seems to be working fine, but of course IntraACL is not functioning.

---------------

So what should I do now to get IntraACL working on my wiki?

**Comment by vitalif** [comment]
First of all you need to get the error information by setting $wgShowSQLErrors = true;

**Comment by vitalif** [comment]
You can now try the patch for 1.25. I've just committed it to master.
