### ISSUE TITLE
Questions regarding patch for MW 1.25 - Bug in patch for MW 1.24.1?

### ISSUE THREAD

**Issue by hermannschwaerzlerUIBK** [mediawiki4intranet/IntraACL#40]
Hi everybody,

I am working on a patch for MW 1.25. Starting with the patch for 1.24.1 I was able to almost finish that task. The patch tool was able to apply most of the changes (with some offsets). Others I was able to apply manually by comparing 1.25-code and 1.24-code. But there are two changes that I can't figure out how to apply:
``` diff
--- includes/api/ApiQueryBacklinks.php
+++ includes/api/ApiQueryBacklinks.php
@@ -367,6 +372,11 @@
        private function extractRowInfo( $row ) {
                $this->pageMap[$row->page_namespace][$row->page_title] = $row->page_id;
                $t = Title::makeTitle( $row->page_namespace, $row->page_title );
+               // <IntraACL>
+               if ( !$t->userCan( 'read' ) ) {
+                       continue;
+               }
+               // </IntraACL>
                $a = array( 'pageid' => intval( $row->page_id ) );
                ApiQueryBase::addTitleInfo( $a, $t );
                if ( $row->page_is_redirect ) {
@@ -379,7 +389,13 @@
 
        private function extractRedirRowInfo( $row ) {
                $a['pageid'] = intval( $row->page_id );
-               ApiQueryBase::addTitleInfo( $a, Title::makeTitle( $row->page_namespace, $row->page_title ) );
+               $t = Title::makeTitle( $row->page_namespace, $row->page_title );
+               // <IntraACL>
+               if ( !$t->userCan( 'read' ) ) {
+                       continue;
+               }
+               // </IntraACL>
+               ApiQueryBase::addTitleInfo( $a, $t );
                if ( $row->page_is_redirect ) {
                        $a['redirect'] = '';
                }
```
I think I know where to put that in the 1.25-code but what makes me wonder is this: Did this patch really work in 1.24?
There are two ``continue``s that are not inside a loop! The two functions they are in *are in fact called inside a loop*, but ``continue`` does not work that way, does it? You can't ``continue`` a loop from inside a function called in that loop, can you?
Or am I missing something?

**Comment by vitalif** [comment]
You're right, it seems like a bug :) it should be ```return``` instead of ```continue```.
Although there's also a warning at this line ```$a['pageid'] = intval( $row->page_id );```, because there's no ```$a``` defined at that point...

**Comment by vitalif** [comment]
Moreover, that bug was there since patch for v1.19!
Thanks, I've just fixed it in master.
Pull request with 1.25 patch is welcome.
