### ISSUE TITLE
Trouble installing IntraACL into MW 1.25.2

### ISSUE THREAD

**Issue by obviouslygene** [mediawiki4intranet/IntraACL#41]
MW 1.25.2
PHP 5.4.16
Apache 2.2.15
postgresql 9.2.13

Hi guys, currently with a working MW, tried installing IntraACL but keep getting a "DB connection error: No database connection" on update.php. When I head to the url on the browser, I get this "A database query error has occurred. This may indicate a bug in the software.". 
I checked postgresql logs and found that I keep getting "ERROR:  relation "category_closure" does not exist at character 86
STATEMENT:  SELECT /* IntraACL_SQL_Util::getParentCategoryIDs xx.xx.xx.xx */  category_id  FROM "category_closure"   WHERE page_id = '1'"
I traced the error to the intraacl-functions.sql file, it seems like its unable to run this.
Anyone met with this error before?
I tried searching everywhere but not many answers with pgsql involved.

Thank you!
gene

**Comment by obviouslygene** [comment]
Sorry just got more error logging from it.

A database query error has occurred. This may indicate a bug in the software.

Query:
SELECT category_id FROM "category_closure" WHERE page_id = '1'
Function: IntraACL_SQL_Util::getParentCategoryIDs
Error: 42P01 ERROR: relation "category_closure" does not exist LINE 1: ...entCategoryIDs 10.67.17.183 */ category_id FROM "category_... ^
Backtrace:

#0 /usr/share/mediawiki/includes/db/DatabasePostgres.php(539): DatabaseBase->reportQueryError('ERROR:  relatio...', '42P01', 'SELECT  categor...', 'IntraACL_SQL_Ut...', false)
#1 /usr/share/mediawiki/includes/db/Database.php(1205): DatabasePostgres->reportQueryError('ERROR:  relatio...', '42P01', 'SELECT  categor...', 'IntraACL_SQL_Ut...', false)
#2 /usr/share/mediawiki/includes/db/Database.php(1726): DatabaseBase->query('SELECT  categor...', 'IntraACL_SQL_Ut...')
#3 /usr/share/mediawiki/extensions/IntraACL/storage/SQL_Util.php(158): DatabaseBase->select('category_closur...', 'category_id', Array, 'IntraACL_SQL_Ut...')
#4 /usr/share/mediawiki/extensions/IntraACL/includes/Evaluator.php(396): IntraACL_SQL_Util->getParentCategoryIDs(1)
#5 /usr/share/mediawiki/extensions/IntraACL/includes/Evaluator.php(349): IACLEvaluator::hasSD(Object(Title), 1, 0, 1)
#6 /usr/share/mediawiki/extensions/IntraACL/includes/Evaluator.php(134): IACLEvaluator::userCan_Switches(Object(Title), Object(User), 'read')
#7 [internal function]: IACLEvaluator::userCan(Object(Title), Object(User), 'read', '')
#8 /usr/share/mediawiki/includes/Hooks.php(209): call_user_func_array('IACLEvaluator::...', Array)
#9 /usr/share/mediawiki/includes/Title.php(2059): Hooks::run('userCan', Array)
#10 /usr/share/mediawiki/includes/Title.php(2507): Title->checkPermissionHooks('read', Object(User), Array, 'secure', false)
#11 /usr/share/mediawiki/includes/Title.php(1933): Title->getUserPermissionsErrorsInternal('read', Object(User), 'secure')
#12 /usr/share/mediawiki/includes/MediaWiki.php(185): Title->getUserPermissionsErrors('read', Object(User))
#13 /usr/share/mediawiki/includes/MediaWiki.php(566): MediaWiki->performRequest()
#14 /usr/share/mediawiki/includes/MediaWiki.php(414): MediaWiki->main()
#15 /usr/share/mediawiki/index.php(41): MediaWiki->run()
#16 {main}

**Comment by obviouslygene** [comment]
I finally realised why its not working, because it doesnt work with pgsql. im sorry guys. gonna close this.

**Comment by vitalif** [comment]
I think it can be reopened to finally implement postgresql support :)

**Comment by obviouslygene** [comment]
holy crap. for real?!

**Comment by vitalif** [comment]
I'm sure it only needs slight modifications to work with pg. The only piece of functionality that must be fully rewritten is my permission check stored procedure, but it's optional and it's slowing wiki up anyway :) (although without it page listings aren't split into pages correctly)

**Comment by obviouslygene** [comment]
Awesome Vitaly! Can't wait for the implementation :)

**Comment by vitalif** [comment]
Please try the latest master, I've just committed basic support for PostgreSQL. You may still get database query errors, reopen the issue in that case...

**Comment by obviouslygene** [comment]
Thank you Vitaliy! Gonna try it these few days. Gotta get approval to pull the latest into my mirror.

Eugene
