### ISSUE TITLE
IntraACL

### ISSUE THREAD

**Issue by VolkovVD** [mediawiki4intranet/IntraACL#42]
Hi.

Why dialog IntraACL looks like this?

![_ _102915_034657_pm](https://cloud.githubusercontent.com/assets/5844062/10813866/75323d02-7e54-11e5-96e0-7fed6a8a69f9.jpg)

I am using code bundle http://wiki.4intra.net/Mediawiki4Intranet

Volkov Vital

**Comment by vitalif** [comment]
Probably because you're using PHP older than 5.4.0 and have short_open_tag disabled. short_open_tag affected <?= ?> prior to 5.4.0. So either update your PHP or enable short_open_tag in php.ini.

**Comment by vitalif** [comment]
I'm closing the issue, please reopen if you still have the problem :)
