### ISSUE TITLE
Subpages does not inherit ACL from parent?

### ISSUE THREAD

**Issue by engren** [mediawiki4intranet/IntraACL#43]
Hi

I am having no luck with subpages inheriting the ACL from the parent page. I am hoping it's just a configuration option, but I am not sure and Google is not helping me much.

MediaWiki: 1.24.1
IntraACL: 2.1.6

Example; ACL set on namespace MyNamespace, and I have a custom ACL allowing most users to see MyNamespace:PrivateDocument/PublicDocument/

I would expect MyNamespace:PrivateDocument/PublicDocument/Clarification/ and MyNamespace:PrivateDocument/PublicDocument/Bananas/ to be inheriting the ACL from MyNamespace:PrivateDocument/PublicDocument.

**Comment by vitalif** [comment]
There is no such feature in IntraACL as the inheritance of ACL to subpages :)

**Comment by engren** [comment]
Consider this a feature request then! :-)

Not looking forward to adding ACLs to 300+ subpages manually.

**Comment by vitalif** [comment]
In fact even my colleagues want this feature :) so I think I'll have to implement it some day.
Btw, you may try to use categories for ACL inheritance.

**Comment by engren** [comment]
Is there anything I can do to help you prioritze this?

(Unfortunally, categories won't help me)

Sidenote; Upgrading IntraACL from 2.1.6 to 2.1.8 (or the upcoming version that hopefully includes inheritation of ACLs) - is that a matter of replacing the relevant IntraACL files, or would I have to repatch MediaWiki aswell?

**Comment by vitalif** [comment]
ACLs for subpages ("tree ACLs") implemented in master, you can try them out.
