### ISSUE TITLE
Howto apply Mediawiki updates?

### ISSUE THREAD

**Issue by derhansen** [mediawiki4intranet/IntraACL#44]
I'm using IntraACL in my MediaWiki installation and I'm missing a section in the documentation on howto apply MediaWiki updates (e.g. Security Updates) to a MediaWiki installation with IntraACL.

I would guess the process is as following:

* Make a backup of all files and the media database
* Decompress new MediaWiki package
* Restore files from backup (e.g. LocalSettings,php, images, uploads)
* Upgrade Extensions (git pull origin master for IntraACL)
* Proceed with installation of IntraACL as described in manual http://wiki.4intra.net/IntraACL

Is this the suggested way of upgrading MediaWiki with IntraACL?

**Comment by vitalif** [comment]
Your method is correct for major updates, but in case of minor ones you may just overwrite all mediawiki code files and then reapply the IntraACL patch.
