### ISSUE TITLE
Parse error while creating group

### ISSUE THREAD

**Issue by kush789** [mediawiki4intranet/IntraACL#51]
When I try to make a new group from the following page:

`mediawiki/index.php?title=Special:IntraACL&action=group`

The script dies in the middle, and there is just a blank page (after submitting the form). I enabled debugging (allowed php to show errors), this is what I get after submitting the form.

`Parse error: syntax error, unexpected '[' in /var/www/resources/mediawiki/extensions/IntraACL/includes/Definition.php on line 507 `

Would really appreciate some help!
Thanks

**Comment by vitalif** [comment]
Is your php older than 5.4?

**Comment by kush789** [comment]
Yes, 5.3. Would that be the root of the problem? I apologize if that sounds trivial to solve, I haven't really worked on php before.

**Comment by kush789** [comment]
When I checked the requirements for IntraACL, php version was required to be >= 5.3

**Comment by vitalif** [comment]
Okay, there's really just a few places with php 5.4 array syntax, I've changed them all to array(). Try out the new master. Although I still think you should upgrade your php to at least 5.4, it's a 2012 version :)

**Comment by kush789** [comment]
Thank you so much!
