### ISSUE TITLE
php code displayed on ACL special page

### ISSUE THREAD

**Issue by SamWMTaylor** [mediawiki4intranet/IntraACL#52]
Hello,
We've installed the IntraACL extension on our wiki but we're seeing php code displayed in the both fields and buttons when we access the extension in Special Pages.

I've attached some screen shots so you can see what is happening.

The only entries in our httpd (apache) log which mention IntraACL are this:

[Wed May 18 14:36:01 2016] [error] [client 10.#.#.#] File does not exist: /var/www/mediawiki/<, referer: http://###.com/index.php?title=Special:IntraACL&action=acl

Has anyone encountered this problem before and know how to fix?  Any thoughts greatly appreciated.

![create acl definition](https://cloud.githubusercontent.com/assets/18721660/15361062/ef8bfa64-1d07-11e6-8076-2e8e6b55bf39.jpg)

![manage acl](https://cloud.githubusercontent.com/assets/18721660/15361079/0439f5c4-1d08-11e6-9cc3-df2655f10c3d.jpg)

![manage quick acl](https://cloud.githubusercontent.com/assets/18721660/15361088/0dbd25e4-1d08-11e6-9048-3a2a74143326.jpg)

**Comment by SamWMTaylor** [comment]
PS: Sorry forgot to add the following:
MediaWiki: 1.24.1
PHP: 5.3.3 (apache2handler)
MySQL: 5.1.73
IntraACL: 2.2.0-dev
Skin: Vector

**Comment by vitalif** [comment]
This is a frequent problem, either update your PHP or enable short_open_tag in php.ini

**Comment by vitalif** [comment]
<?= ?> tags are not "short" in php, but certain old versions have a bug which makes php treat them so

**Comment by vitalif** [comment]
Reopen if it doesn't help :-)

**Comment by SamWMTaylor** [comment]
Hello Vitaliy,

Your suggestion: "enable short_open_tag in php.ini" worked great.

Thanks so much for your help.
