### ISSUE TITLE
IntraACL with DynamicSidebar

### ISSUE THREAD

**Issue by Serze** [mediawiki4intranet/IntraACL#54]
Having a problem intregrating IntraACL with DynamicSidebar. I am wondering if it is possible to show the user's Namespaces on the MediaWiki:Sidebar that they have access too (within IntraACL).

Thanks!

**Comment by vitalif** [comment]
I think it's possible with some dirty hacks like checking if the resulting link in html is not a link to "Access_denied", or by creating an indicator article with known name in each namespace and using TemplatedPageList to list them and strip the page name in template... (this is our extension, see mediawiki4intranet repos; I don't know if the original DynamicPageList is checking read permissions)

**Comment by kaiser-nero** [comment]
Is there any example that you have of this? And thanks for the swift response. This extension is truly a life saver.

**Comment by vitalif** [comment]
this is not trivial, try to figure it out yourself :) something like
{{#templatedpagelist:
prefix=A
level=0
output=template
template=NsList
}}
and in NsList use {{FULLPAGENAME}} with {{#replace}} to remove page name (:A)

**Comment by kaiser-nero** [comment]
I'm just wondering how to query against the user's ACL permissions to get the Sidebar to show certain links if they are in certain groups.

I'm still struggling with this task.

Btw. Is there a donation place somewhere?

**Comment by vitalif** [comment]
There is no direct solution for it, but TemplatedPageList hides non-readable pages in output. So it is possible to use this feature to list readable namespaces. Like the following:
1) create pages with same name "A" in all namespaces, Main:A, Talk:A etc
2) install ParserFunctions and TemplatedPageList
3) create template Template:NsList with content `* {{#replace:{{FULLPAGENAME}}|:A|}}`
4) use the query from comment above - it should list readable namespaces
Note this will only work to check read access, not edit. Currently there's no parser function to check if the user has edit access to pages.
You may send a donation via paypal to vitalif@mail.ru :)

**Comment by kaiser-nero** [comment]
Thanks I will give this a go!

**Comment by kaiser-nero** [comment]
Figured it out. Thanks vita!

**Comment by Serze** [comment]
So I figured it out, it works and it shows up on the sidebar according to your access. But I need it to hyperlink to the namespace. Example: Namespace:Main

It needs to link to Namespace:Main
