### ISSUE TITLE
Files within namespaces

### ISSUE THREAD

**Issue by kaiser-nero** [mediawiki4intranet/IntraACL#55]
Are files within namespace (pictures and other file types) protected when you set permissions for a namespace?

**Comment by vitalif** [comment]
Do you mean File namespace? Yes, but you should setup img_auth.php to serve image contents to protect images from direct file access

**Comment by kaiser-nero** [comment]
The img_auth.php serves images only to logged in users. How do I further protect namespaces using IntraACL permissions?

**Comment by vitalif** [comment]
What do you mean?

**Comment by kaiser-nero** [comment]
When uploading pictures on a namespace with InterACL permissions, a person only is able to open files/images under the namespace they have access too.

**Comment by vitalif** [comment]
All files/images in MediaWiki are in namespace File, aren't they? Or are you using an extension to have files in multiple namespaces?
