### ISSUE TITLE
IntraACL compatibility with CKEditor

### ISSUE THREAD

**Issue by kaiser-nero** [mediawiki4intranet/IntraACL#56]
When CKEditor is enabled IntraACL will not work.

I have tried using:

require_once "$IP/extensions/WYSIWYG/WYSIWYG.php";
$wgGroupPermissions['*']['wysiwyg']=true; // for all users
$wgGroupPermissions['registered_users']['wysiwyg']=true; // or only for registered users
$wgFCKEditorExcludedNamespaces = array(NS_SPECIAL);

It seems to not work, do you have any insight?

**Comment by vitalif** [comment]
What do you mean by "will not work"? What does it do instead of working?)

**Comment by kaiser-nero** [comment]
Full explanation:

Manage ACL does not populate.

Create ACL.
- Modify definition: Does not autofill
- Definition target: Does not autofill and when you enter an object and click off it does not fill in the []'s

Create group:
- Same autofill and object issues as Create ACL.

Manage groups:
- Does not autofill with the groups.

All of this starts to work when I disable WYSIWYG (FCKEditor)

**Comment by vitalif** [comment]
Do you mean Special:IntraACL stops working when FCKEditor is installed? This is strange, I've just checked it on my wiki with CKEditor installed, with the following config:
```
require_once("extensions/WYSIWYG/WYSIWYG.php");

$wgGroupPermissions['*']['wysiwyg'] = true;
$wgDefaultUserOptions['cke_show'] = 'richeditor';
$wgDefaultUserOptions['riched_use_toggle'] = true;
$wgDefaultUserOptions['riched_start_disabled'] = false;
$wgDefaultUserOptions['riched_toggle_remember_state'] = true; // working/bug?

##These are not compatible with WYSIWYG
$wgFCKEditorExcludedNamespaces[] = NS_MEDIAWIKI;
$wgFCKEditorExcludedNamespaces[] = NS_TEMPLATE;
```
and Special:IntraACL works without problem...

**Comment by kaiser-nero** [comment]
![intraacl](https://cloud.githubusercontent.com/assets/19697472/15759329/7e6a6d32-28cb-11e6-895c-e6e76df218fd.png)

I've inputted your code above but I still am getting the same output.

**Comment by kaiser-nero** [comment]
Is there any debug that I can use to get the code to you to see what is wrong?

**Comment by vitalif** [comment]
Check browser console (press F12) and check for javascript errors. I think this is some kind of js issue.

Btw, are you using WYSIWYG from here https://github.com/Mediawiki-wysiwyg/WYSIWYG-CKeditor?

**Comment by kaiser-nero** [comment]
Yes I am using that WYSIWYG

And when I run the debugger I get:

Line: 961
Error: Unable to get property 'style' of undefined or null reference

**Comment by kaiser-nero** [comment]
I even tried to install a javascript debugger on chrome and had 0 errors when loading the pages.

**Comment by kaiser-nero** [comment]
Is there a default namespace I can use?

https://www.mediawiki.org/wiki/Extension_default_namespaces

**Comment by kaiser-nero** [comment]
Continuing to try and troubleshoot, but still failing.

**Comment by kaiser-nero** [comment]
Is there a way to disable the CKEditor extension on the Special pages using Common.js?

**Comment by vitalif** [comment]
> Line: 961 Error: Unable to get property 'style' of undefined or null reference

In what script?

**Comment by vitalif** [comment]
> Is there a way to disable the CKEditor extension on the Special pages using Common.js?

As I understand CKEditor should not be enabled on Special:IntraACL without any additional configuration... Special:IntraACL isn't a regular "edit page".

**Comment by kaiser-nero** [comment]
Have you looked into this? I still can't seem to figure it out. When you use IntraACL and CKEditor do they work for you?

**Comment by kaiser-nero** [comment]
I did get this error while in the Create New ACL Definition page while trying to click the "All" "Manage rights of pages" "All" "Edit" "Create" "Delete" "Move" "Change this ACL":

ReferenceError: AE is not defined
&nbsp;/example.com/index.php?title=Special:IntraACL&action=acl:81

ReferenceError: AE is not defined
&nbsp;/example.com/index.php?title=Special:IntraACL&action=acl:83

ReferenceError: AE is not defined
&nbsp;/example.com/index.php?title=Special:IntraACL&action=acl:88

ReferenceError: AE is not defined
&nbsp;/example.com/index.php?title=Special:IntraACL&action=acl:90

ReferenceError: AE is not defined
&nbsp;/example.com/index.php?title=Special:IntraACL&action=acl:92

ReferenceError: AE is not defined
&nbsp;/example.com/index.php?title=Special:IntraACL&action=acl:94

ReferenceError: AE is not defined
&nbsp;/example.com/index.php?title=Special:IntraACL&action=acl:86

ReferenceError: AE is not defined
&nbsp;/example.com/index.php?title=Special:IntraACL&action=acl:97

**Comment by kaiser-nero** [comment]
Does this help?

**Comment by kaiser-nero** [comment]
<input type="checkbox" id="act_manage" onclick="AE.act_change(this)" onchange="AE.act_change(this)" />

It has something to do with your AE. variable when CKEditor is enabled.

**Comment by kaiser-nero** [comment]
I also get this on Manage ACL when I uncheck everything:

ReferenceError: change_filter is not defined
&nbsp;/wiki.ranchehrlo.ca/index.php?title=Special:IntraACL&action=acllist:50

ReferenceError: change_filter is not defined
&nbsp;/wiki.ranchehrlo.ca/index.php?title=Special:IntraACL&action=acllist:47

ReferenceError: change_filter is not defined
&nbsp;/wiki.ranchehrlo.ca/index.php?title=Special:IntraACL&action=acllist:52

ReferenceError: change_filter is not defined
&nbsp;/wiki.ranchehrlo.ca/index.php?title=Special:IntraACL&action=acllist:53

ReferenceError: change_filter is not defined
&nbsp;/wiki.ranchehrlo.ca/index.php?title=Special:IntraACL&action=acllist:54

ReferenceError: change_filter is not defined
&nbsp;/wiki.ranchehrlo.ca/index.php?title=Special:IntraACL&action=acllist:55

ReferenceError: change_filter is not defined
&nbsp;/wiki.ranchehrlo.ca/index.php?title=Special:IntraACL&action=acllist:59

ReferenceError: change_filter is not defined
&nbsp;/wiki.ranchehrlo.ca/index.php?title=Special:IntraACL&action=acllist:61

**Comment by kaiser-nero** [comment]
I've come across a new finding:

When CKEditor is loaded this line looks like:

mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);

When it is disabled it looks like this:

mw.loader.state({"user":"ready","user.groups":"ready"});mw.loader.load(["ext.intraacl.acllist","site","mediawiki.user","mediawiki.hidpi","mediawiki.page.ready","mediawiki.searchSuggest"]);

It is missed the "ext.interaacl.acllist" in the mw.loader.load

**Comment by vitalif** [comment]
Yes, this seems the cause. Does the rest of page HTML code contain ext.intraacl.acllist module? If not, it's definitely the cause.
But it's strange... I think the bug is in CKEditor, not in IntraACL. Unfortunately I can't reproduce it by now so I can't give an advice how to fix it.

**Comment by vitalif** [comment]
Btw what's the version of your mediawiki? Mine is 1.26

**Comment by kaiser-nero** [comment]
Mine is that latest stable: 


Product	Version
MediaWiki	1.26.2
PHP	5.5.9-1ubuntu4.17 (apache2handler)
MySQL	5.5.49-0ubuntu0.14.04.1

**Comment by kaiser-nero** [comment]
Is there a way to force "ext.interaacl.acllist" to load on all pages within mw.loader.load()

**Comment by vitalif** [comment]
Ok... and what branch of the WYSIWYG repo are you using?

**Comment by kaiser-nero** [comment]
1.5.6_0 [B551+01.05.2016]

**Comment by kaiser-nero** [comment]
IntraACL	2.2.0-dev
WYSIWYG editor	1.5.6_0 [B551+03.06.2016], CKEditor 4.5.8 (revision c1fc9a9)

**Comment by kaiser-nero** [comment]
"But it's strange... I think the bug is in CKEditor, not in IntraACL. Unfortunately I can't reproduce it by now so I can't give an advice how to fix it."

- I completely agree with you. Is there maybe a set of arguments we can use within CKEditor to ignore the mw.loader.load for IntraACL?

**Comment by vitalif** [comment]
Ah ok. It's very simple to fix, it's just an idiotic error in WYSIWYG. They just deleted the declarations of all resource modules except their own. Just change line "$wgResourceModules = array(" ... to "$wgResourceModules += array(" in WYSIWYG.php to fix it.

Btw, CKeditor_v45 branch worked ok in my wiki.

**Comment by kaiser-nero** [comment]
Wow, amazing. Thanks vlad! Close this off.

**Comment by vitalif** [comment]
I'm not Vlad but ok :)

**Comment by kaiser-nero** [comment]
Corrected.. ID 10 T error.... (idiot error) haha. Damn I'm excited.
