### ISSUE TITLE
Hide Create new ACL definition && Create a group

### ISSUE THREAD

**Issue by kaiser-nero** [mediawiki4intranet/IntraACL#57]
Is there a way to hide these two tabs and block access to them based on $haclgSuperGroups = array('sysop'); ?

**Comment by kaiser-nero** [comment]
Still having problems locating the menu in Special:IntraACL. I have checked everywhere, I would have thought they would have been in /templates/

**Comment by vitalif** [comment]
Currently there's no option to disable these tabs, all users can create ACLs for pages. Look in open issues, there's a similar request to block users from creating ACLs.

**Comment by kaiser-nero** [comment]
Ok thank you.

But where are those buttons located in? What file, so I can edit their styling.

**Comment by vitalif** [comment]
They're in function _actions inside includes/ACLSpecial.php

**Comment by kaiser-nero** [comment]
Fixed:
$actions = array('acllist', 'grouplist');
Was:
$actions = array('acllist', 'acl', 'quickaccess', 'grouplist', 'group');

**Comment by kaiser-nero** [comment]
Thanks again!

**Comment by vitalif** [comment]
User may go directly to ACL:Page/Something and create it
