### ISSUE TITLE
Manage Groups

### ISSUE THREAD

**Issue by 0x539-nero** [mediawiki4intranet/IntraACL#59]
Is there anyway it could parse the members and managers into their own lists?

I could hide the definition textarea but how would I put members into their own textare and managers into their own textarea (or listbox)?

**Comment by vitalif** [comment]
What do you want to achieve by this?

**Comment by Serze** [comment]
So my users are a bit "unexperienced", so I would like them to see an overview of who is in the groups.

The listboxes (one for users and one from managers) would help visualize who are in the groups.

When they see the code: {{#member: members = User:Name.Lastname}}
{{#manage group: assigned to = User:Name.Lastname}}

It may be confusing to them.

**Comment by Serze** [comment]
This would be a great addition to user's who don't understand code, but use the Group Editor.

**Comment by vitalif** [comment]
Similar listboxes show up under the autocompleted member/manager editboxes...

**Comment by Serze** [comment]
Yes, but it would give an overview of it to the user. My users who are using this would like to see an overview.

**Comment by Serze** [comment]
Is there anyway we can make this possible?

**Comment by Serze** [comment]
I could donate a little to make this happen as well.

**Comment by Serze** [comment]
Any update on this?

**Comment by Serze** [comment]
Any idea on this vitalif?

**Comment by vitalif** [comment]
I think it's not too fast to implement :)

**Comment by Serze** [comment]
Thank you so much :)

**Comment by Serze** [comment]
Any progress sir? :dancer:

**Comment by 0x539-nero** [comment]
Anything?

**Comment by vitalif** [comment]
I don't like the idea of adding listboxes.. where to place them? Maybe text notes with user lists will be sufficient? or do you also want to hide the code textarea?..

**Comment by 0x539-nero** [comment]
I want to hide the code textarea which I already did by using: style="display: none;" -- but I would like to be able to see the users in a nice list without all the messy code.

**Comment by 0x539-nero** [comment]
The text notes work as well.

**Comment by 0x539-nero** [comment]
:dart:
