### ISSUE TITLE
Rights Graph object issue

### ISSUE THREAD

**Issue by 0x539-nero** [mediawiki4intranet/IntraACL#61]
What does this mean?

Fatal error: Call to a member function getPrefixedText() on a non-object in /var/www/html/wiki.ranchehrlo.ca/extensions/IntraACL/includes/ACLSpecial.php on line 383

When I click view rights graph.

**Comment by vitalif** [comment]
This means there's some kind of bug... what types of ACLs do you have in your wiki?

**Comment by Serze** [comment]
I have namespaces/pages only.
