### ISSUE TITLE
IntraACL broken with MediaWiki 1.27

### ISSUE THREAD

**Issue by siv-radar** [mediawiki4intranet/IntraACL#64]
Trying to install the IntraACL extension (from github master) on a fresh MediaWiki 1.27 install (with the LdapAuthentication plugin), fails due to the missing patch-file for MediaWiki 1.27.

I tried applying the patch for 1.26 (IntraACL-MediaWiki-1.26.diff), however, most hunks failed to apply, additionally at least 2 files were missing/moved.

Is support for MediaWiki 1.27 planned? If so is there any timeline?

Should there be anything I can support you with - let me know!
regards

**Comment by vitalif** [comment]
You can help by contributing a rebased patch :)
Some time I'll work on it but I don't know when. I'm not planning to update my wikis to 1.27 yet. As I understand it has almost no new features

**Comment by vitalif** [comment]
You can help by contributing a rebased patch :)
Some time I'll work on it but I don't know when. I'm not planning to update my wikis to 1.27 yet. As I understand it has almost no new features

**Comment by ITbugoff** [comment]
Hello Stoiko,

we have created a re-based patch for MW 1.27. Take a look here: https://github.com/ITbugoff/MediaWiki and let us know if it worked for you.

Regards,
Oleksii

**Comment by vitalif** [comment]
I've rebased the patch to 1.27.2 and fixes some issues. You can try it out from master branch :)
