### ISSUE TITLE
install Patch

### ISSUE THREAD

**Issue by MCazy** [mediawiki4intranet/IntraACL#67]
Hello,

I have installed mediawiki version 1.26 on my windows server. I would like to install IntraACL. I do the following steps:

git clone https://github.com/mediawiki4intranet/IntraACL

copy the extracted folder to my extentions folder 

require_once('extensions/IntraACL/includes/HACL_Initialize.php');
enableIntraACL();

but when I open my cmd as admin and do that in my wiki root folder patch -p1 < extensions/IntraACL/patches/IntraACL-MediaWiki-1.26.diff receive a error message in the commandline patch misspelled or could not be found. it's the correct folder and so on what can I do?

Kind regards

**Comment by vitalif** [comment]
It's an incorrect OS :) use patch from here http://gnuwin32.sourceforge.net/packages/patch.htm

**Comment by MCazy** [comment]
thx 4 the quick response I try it
