### ISSUE TITLE
Problems with ACL

### ISSUE THREAD

**Issue by 0x539-nero** [mediawiki4intranet/IntraACL#68]
I am continuously getting what does this mean?

[Mon Nov 07 15:12:20 2016] [error] [client 10.10.2.107] PHP Notice:  Uninitialized string offset: 2 in /var/www/website.com/extensions/IntraACL/includes/Definition.php on line 110, referer: https://website.com/kb/index.php?title=Special:IntraACL&action=acl&sd=Page%2FIntraACL
[Mon Nov 07 15:12:20 2016] [error] [client 10.10.2.107] PHP Notice:  Uninitialized string offset: 3 in /var/www/website.com/extensions/IntraACL/includes/Definition.php on line 112, referer: https://website.com/kb/index.php?title=Special:IntraACL&action=acl&sd=Page%2FIntraACL
[Mon Nov 07 15:12:20 2016] [error] [client 10.10.2.107] PHP Notice:  Uninitialized string offset: 0 in /var/www/website.com/extensions/IntraACL/includes/Definition.php on line 112, referer: https://website.com/kb/index.php?title=Special:IntraACL&action=acl&sd=Page%2FIntraACL
[Mon Nov 07 15:12:20 2016] [error] [client 10.10.2.107] PHP Notice:  Uninitialized string offset: 2 in /var/www/website.com/extensions/IntraACL/includes/Definition.php on line 112, referer: https://website.com/kb/index.php?title=Special:IntraACL&action=acl&sd=Page%2FIntraACL

**Comment by 0x539-nero** [comment]
Also getting this:

[Mon Nov 07 16:06:53 2016] [error] [client 10.10.2.107] PHP Warning:  Invalid argument supplied for foreach() in /var/www/website.com/extensions/IntraACL/includes/AjaxConnector.php on line 368, referer: https://website.com/kb/index.php?title=Special:IntraACL&action=acl&sd=Namespace%2FIT

**Comment by 0x539-nero** [comment]
I am now experiencing all of my language files not working. Everything is show up as:

<hacl_acllist>
or
<hacl_acllist_hello>

**Comment by vitalif** [comment]
Thanks, these were possible bugs. Just fixed in master.

**Comment by 0x539-nero** [comment]
You're welcome this extension kicks ass.
