### ISSUE TITLE
Is it ok 'View rights on a graph'

### ISSUE THREAD

**Issue by luciagirasoles** [mediawiki4intranet/IntraACL#73]
I just need to know if what is shown in View rights on a graph is ok or I need to add an extension.

![image](https://cloud.githubusercontent.com/assets/26725925/24510940/26596c72-1530-11e7-9801-597ab8a7b58d.png)

OS: Windows
MediaWiki	1.27.1
PHP	5.6.30 (apache2handler)

**Comment by vitalif** [comment]
yeah, you need graphviz
