### ISSUE TITLE
Patch 1.27 Error // $_SERVER[SERVER_NAME] is empty

### ISSUE THREAD

**Issue by centaure** [mediawiki4intranet/IntraACL#75]
I am running into problem that looks exactly same as that reported in Issue #63 .
Any suggestions on how to fix it?

I installed MW 1.27.1. Got the patch from your git repository.
Applied patch ... no issues/errors shown there. But when I try to run update.php, I get following error thrown.
On the web-browser I see the ACL tab. But trying to do anything with ACL tab throws Error page.

sudo php maintenance/update.php
** WARNING: IntraACL security checks are disabled because
** $_SERVER[SERVER_NAME] is empty, which probably means we are in console

**Comment by vitalif** [comment]
What exact error do you get?

**Comment by centaure** [comment]
If I click on the link on the ACL tab: Create this definition with IntraACL editor.
the browser shows "Exception encountered, of type "Error" "

**Comment by centaure** [comment]
There were two errors reported during the m

1. PHP Fatal error:  Uncaught Error: Call to undefined function wfMsg() in /var/lib/wiki/includ                                              es/parser/Parser.php:3680

I fixed this one by replacing wfMsg() to wfMsg()->text().

2. Creating IntraACL 'Permission denied' page...PHP Notice:  Undefined offset: 2 in /var/lib/wiki/includes/parser/Parser.php on line 3927

Here is the line 3927 from Parser.php :-
               # Cache miss, go to the database
                list( $text, $title, $canRead ) = $this->fetchTemplateAndTitle( $title );

I dont know how to fix #2?

**Comment by vitalif** [comment]
Ok, I've fixed both problems + added a rebased patch for 1.27.2
