### ISSUE TITLE
IntraACL ToolBar

### ISSUE THREAD

**Issue by mukulagrawal78** [mediawiki4intranet/IntraACL#81]
# @vitalif , I would like not to show the IntraACL toolbar in the wikitext editor. Any ideas if how I can switch it off ?

![capture](https://cloud.githubusercontent.com/assets/5083036/25774836/33d97ed0-324c-11e7-9a7b-38774e21e83b.PNG)

**Comment by vitalif** [comment]
Just added a config variable for you, see the commit

**Comment by centaure** [comment]
Thank you!
