### ISSUE TITLE
Page updates are failing due to misconfigured trigger (do_delete_category_closure_catlinks)

### ISSUE THREAD

**Issue by D4rkMindz** [mediawiki4intranet/IntraACL#93]
We use IntraACL in our media wiki. Its really important to us and our customers.
Since tuesday this week (14. May 2019) we get the following error message (after setting `$wgShowSQLErrors = true;`)
```SQL
DELETE FROM `categorylinks` WHERE cl_from = '<some ID>' AND cl_to = '<something>'
```
This query fails due 
`1305 PROCEDURE <database name>.do_delete_category_closure_catlinks does not exist`

[This discussion](https://www.mediawiki.org/wiki/Topic:T4pejoifg3blbfcd) lets me assume that it is a problem with IntraACL's triggers (see [storage/intraacl-functions-mysql.sql](https://github.com/mediawiki4intranet/IntraACL/blob/master/storage/intraacl-functions-mysql.sql))

**Comment by vitalif** [comment]
What did you do with your wiki? Stored procedure can't disappear by itself :)
You can drop table `category_closure` by hand and run `maintenance/update.php` to recreate it along with IntraACL stored procedures.

**Comment by D4rkMindz** [comment]
Well thanks, that worked. 😄 👍
